version: "3.8"

services:
  db:
    image: postgres
    container_name: gerart-database
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports: 
      - 5432:5432
    expose: 
      - 5432
    volumes:
      - /data:/var/lib/postgresql/data:rw
    networks:
      - postgres-compose-network
  
  api:
    build: ./API
    container_name: gerart-api
    env_file:
      - ./envs/postgres.env
    ports:
      - 3000:3000
    expose: 
      - 3000
    depends_on:
      - db
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge